version: "3.3"

services:
  streamer:
      image: fmoriguchi/streamer-videos:0.0.4
      build: .
      ports:
        - "80:8080"
      volumes:
        - file-repository:/tmp

volumes:
  file-repository:
